{
 "title": "Boost Watcher Dashboard",
 "tags": [
  "boost-monitor",
  "ethereum"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Block Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(blocks_processed[5m])", "legendFormat": "Blocks Per Second" }
   ]
  },
  {
   "title": "Total Blocks Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocks_processed", "legendFormat": "Total Blocks" }
   ]
  },
  {
   "title": "Highest Bid Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "eth" } },
   "targets": [
    {
     "expr": "highest_bid_value_block_{block_number}",
     "legendFormat": "Block {{block_number}}"
    }
   ]
  },
  {
   "title": "Gas Used By Highest Bids",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgas" } },
   "targets": [
    {
     "expr": "highest_bid_gas_used_block_{block_number}",
     "legendFormat": "Block {{block_number}}"
    }
   ]
  },
  {
   "title": "Number of Transactions in Highest Bids",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "highest_bid_num_tx_block_{block_number}",
     "legendFormat": "Block {{block_number}}"
    }
   ]
  }
 ]
}